### ISSUE TITLE
配置好了无法访问目标端口

### ISSUE THREAD

**Issue by geekbyter** [vela-security/openresty-ssl-ja3#2]
你好，我配置好了，用bash build.sh，中途没有报任何错误，nginx也能启动

我的配置如下 ：
![image](https://github.com/vela-security/openresty-ssl-ja3/assets/30831453/743f3d13-d65e-4eac-8b9a-3254ca0e9316)

在当前机器里，curl 访问是可以的：
![image](https://github.com/vela-security/openresty-ssl-ja3/assets/30831453/841adf70-94ef-4527-ae57-3792eb25f5e2)

启动了nginx之后，无法访问：
![image](https://github.com/vela-security/openresty-ssl-ja3/assets/30831453/5e8ee13c-0cfa-4b62-915b-ffbe0aefc6ed)
![image](https://github.com/vela-security/openresty-ssl-ja3/assets/30831453/a3d09bf4-4367-42ca-87c5-efa16594ff24)

请问是哪里的问题呀。6363外网ip端口我已经开启了
![image](https://github.com/vela-security/openresty-ssl-ja3/assets/30831453/c810894e-5554-4dc9-b4ed-4743c194083a)

是这么使用的吗？还是其他的用法呢

**Comment by vela-security** [comment]
curl https://127.0.0.1:6363 -k
能访问吗？
如果是有问题，可以再前面添加一个 http请求判断

**Comment by geekbyter** [comment]
感谢你的回复，才看到。
我没解决这个问题，我的服务器已经重置了，然后换了一个方案安装好了。有空再试试你这个。感谢

**Comment by geekbyter** [comment]
你好，不好意思隔了这么久，我配置好了，可以使用了，非常感谢大佬开发这么好的项目，我直接无脑安装一把过，那个nginx-ssl-ja3反而配置半天不成功。
